// Generated by scripts/measure-device-frames.mjs from the images in public/devices/.
// Re-run it after replacing an image; hand edits are overwritten.
import type { Device } from "@/data/projects";

export type DeviceFrame = {
  src: string;
  naturalWidth: number;
  naturalHeight: number;
  /** The screen's box as % of the image; radius is % of the image width. */
  screen: { top: number; left: number; width: number; height: number; radius: number };
};

export const DEVICE_FRAMES: Record<Device, DeviceFrame> = {
  desktop: {
    src: "/devices/laptop.png",
    naturalWidth: 1520,
    naturalHeight: 976,
    screen: {
      top: 3.279,
      left: 7.895,
      width: 84.211,
      height: 81.967,
      radius: 0.449,
    },
  },
  tablet: {
    src: "/devices/tablet.png",
    naturalWidth: 1264,
    naturalHeight: 902,
    screen: {
      top: 3.548,
      left: 2.532,
      width: 94.937,
      height: 92.905,
      radius: 0.54,
    },
  },
  mobile: {
    src: "/devices/phone.png",
    naturalWidth: 446,
    naturalHeight: 906,
    screen: {
      top: 2.208,
      left: 4.484,
      width: 89.686,
      height: 95.585,
      radius: 10.717,
    },
  },
};
